### ISSUE TITLE
On details about the experiments

### ISSUE THREAD

**Issue by tianylin98** [lukemelas/do-you-even-need-attention#1]
In the experiment section of the report, you mention:

> Such a comparison is not exactly fair because the feed-forward model uses stronger training augmentations.

I wonder what the **augmentations** are, for details about the augmentation seems missing from the paper.

**Comment by lukemelas** [comment]
Thanks for the issue. The augmentations are exactly the same as those in DeiT. When you train with the `main.py` file from the DeiT repo, these will all be applied automatically. To be precise, the augmentations are: Rand Augment (9/0.5), Mixup (p=0.8), CutMix (p=1.0), Erasing (p=0.25), DropPath (p=0.1), and Repeated Augmentations.

**Comment by tianylin98** [comment]
Thank you for your reply.
